# Generated by Django 5.0.4 on 2024-06-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmdetails',
            name='firm_pdf',
            field=models.FileField(default=None, max_length=2500, null=True, upload_to='pdf/'),
        ),
    ]
